#玩家最多能有多少牧场 玩家默认是没有的 可以通过指令增加牧场 但不发超出这个最大值限制 读取的数据也是如此
#！暂时没有翻页！功能所以最好不要把这个数字写到>=54喔~
player-max-pasture: 10
#牧场定时检测时长 单位 tick 其实1也消耗不到哪里去 检测时长是用来判断牧场是否需要产出蛋的
pasture-check-time: 1
#牧场宝可梦相处多久尝试产出一次? 单位 tick
pasture-make-egg-time: 18000
#孵化检测 检测玩家背包内的蛋并减少时长
incubation-check-time: 1200
#孵化时长(临时) 蛋在背包内时每经过上方配置的时长进行一次检测并增加剩余时长同时修改lore显示进度 (背包只检测6个蛋哦~)
incubation-time: 24000
#是否离线后继续计时，直到服务器关闭
#当玩家进入服务器后，服务器会有玩家的牧场缓存，直到服务器重启后缓存久没了
#有缓存期间，牧场还能继续工作，但如果服务器启动后，玩家没有进入过服务器，缓存则不存在。
#玩家的牧场也就不会工作，这样可以让忘记至少会启动游戏，而不是直接甩给服务器等牧场
offline-support: true
#红线道具使用后是否消耗
destinyknot-consume: true
#gui配置
gui:
  party-select-gui:
    title: '§3请选择宝可梦'
    elements:
      name: '§3{pokemon_name}'
      lore:
        - '§3点击选择'
  pasture-gui:
    title: '§3牧场 {pasture_id}'
    parent1:
      name: '§3{pokemon_name}'
      lore:
        - '§3点击更换'
    parent2:
      name: '§3{pokemon_name}'
      lore:
        - '§3点击更换'
    egg:
      name: '§3蛋'
      lore:
        - '§3这个蛋需要很久才能孵化。'
        - '§3点击取出'
  pasture-list-gui:
    title: '§3牧场列表'
    elements:
      name: '§3牧场 {pasture_id}'
      lore:
        - '§3当前tick: §r{pasture_tick} §7(低于0则为无法繁殖!)'
        - '§3进度: §a{pasture_progress} %'
