name: ${project.name}
main: ${group]
version: ${version}
api-version: 1.21
depend:
  - FICore
commands:
  cobpasture:
    description: CobPzasture command
permissions:
  cobpasture.cmd.reload:
    default: op
  cobpasture.cmd.makeegg:
    default: op
