name: CobPasture
main: ${group}
version: ${version}
api-version: 1.21
depend:
  - FICore
  - NBTAPI
commands:
  cobpasture:
    description: CobPzasture command
permissions:
  cobpasture.cmd.reload:
    default: op
  cobpasture.cmd.makeegg:
    default: op
  cobpasture.cmd.open:
    default: true
  cobpasture.cmd.add:
    default: op
